### ISSUE TITLE
DistutilsGetoptError: invalid long option 'exclude-dir=': must be a string of length >= 2

### ISSUE THREAD

**Issue by cyrilleverrier** [dealertrack/skipnose#4]
Similar issue as https://github.com/kgrandis/nose-exclude/issues/4, https://github.com/adamchainz/nose-randomly/issues/11, etc.

When invoking through setup.py nosetests (instead of nosetests directly), the following error message is provided:

```
python setup.py nosetests --with-xunit --xunit-file=./build/unit-tests/tests-py2-xunit.xml --exclude-dir=./devtools/
Traceback (most recent call last):
  File "setup.py", line 67, in <module>
    'fsm_rest_api=fsm_rest_api.main:main',
  File "/usr/lib/python2.7/distutils/core.py", line 137, in setup
    ok = dist.parse_command_line()
  File "/home/cyrille/code/infiniband/partitioning_rest_api/.venvs/partitioning_rest_api_py2/local/lib/python2.7/site-packages/setuptools/dist.py", line 299, in parse_command_line
    result = _Distribution.parse_command_line(self)
  File "/usr/lib/python2.7/distutils/dist.py", line 467, in parse_command_line
    args = self._parse_command_opts(parser, args)
  File "/home/cyrille/code/infiniband/partitioning_rest_api/.venvs/partitioning_rest_api_py2/local/lib/python2.7/site-packages/setuptools/dist.py", line 609, in _parse_command_opts
    nargs = _Distribution._parse_command_opts(self, parser, args)
  File "/usr/lib/python2.7/distutils/dist.py", line 564, in _parse_command_opts
    (args, opts) = parser.getopt(args[1:])
  File "/usr/lib/python2.7/distutils/fancy_getopt.py", line 253, in getopt
    self._grok_option_table()
  File "/usr/lib/python2.7/distutils/fancy_getopt.py", line 171, in _grok_option_table
    "must be a string of length >= 2") % long
distutils.errors.DistutilsGetoptError: invalid long option 'with-skipnose': must be a string of length >= 2
```

**Comment by cyrilleverrier** [comment]
See PR https://github.com/dealertrack/skipnose/pull/5

**Comment by pbirnie** [comment]
encountered same issue, PR fixes this, any eta on a new release
